### ISSUE TITLE
B902 requires first parameter named self for __init__ of metaclass

### ISSUE THREAD

**Issue by untitaker** [PyCQA/flake8-bugbear#10]
I have a metaclass defined like this:

    class StorageMeta(type):
        def __init__(cls, name, bases, d):

Naturally B902 flagged the first parameter of `__init__`, but I'm not sure if it's intended in the case of metaclasses. I can imagine arguments for and against this behavior.

**Comment by ambv** [comment]
I figured there's going to create some false positives, hence the B9 marker. I'm happy we did this :)

It's not generally possible to silence *all* possible metaclass false positives but I guess it should at least be possible to silence it for classes that *directly* inherit from `type`, right? Would you have some cycles to come up with a PR for this?

**Comment by untitaker** [comment]
Sure I'd have some cycles for this, but only checking for direct inheritance seems like an unsatisfactory solution to me. I suspect that this sort of lint is better implemented as a runtime check, e.g. as a pytest plugin or something similar (assuming it's a no-go to evaluate module code as flake8-plugin).

**Comment by untitaker** [comment]
So the question is, *is* eval-ing code a no-go?

**Comment by untitaker** [comment]
I guess for now the simple direct base check is enough, see #12
