### ISSUE TITLE
B009 false positive when attribute is not a keyword

### ISSUE THREAD

**Issue by pkolbus** [PyCQA/flake8-bugbear#113]
When the attribute is not a valid Python token, use of `getattr` can be required; flake8-bugbear emits a B009.

Example:

    class DictProxy():

        def __init__(self, data):
            self._data = data

        def __getattr__(self, key):
            try:
                return self._data[key]
            except KeyError:
                raise AttributeError

    d = DictProxy({"foo": "bar", "123": "456"})
    print(d.foo)
    print(getattr(d, "123"))    # B009

The implied suggestion, `d.123`, would be a SyntaxError.

**Comment by cooperlees** [comment]
Good catch. I guess we need to just check that the attribute is all numbers only / is a valid token. PR would be accepted for this.

**Comment by pkolbus** [comment]
Thanks for confirming, I’ll get a PR going soon. My actual use case has a mix of numbers and letters so will check for a valid identifier.
