### ISSUE TITLE
Proposed check: proscribe `not foo == bar`, prefer `foo != bar`

### ISSUE THREAD

**Issue by rpdelaney** [PyCQA/flake8-bugbear#124]
I couldn't find any PEP on this, but it seems that `foo != bar` is widely preferred to `not foo == bar`.

**Comment by cooperlees** [comment]
Thanks for the idea. I dislike seeing this. So I'll accept this. Let's try get one other maintainer to agree before you spend the time tho.

**Comment by rpdelaney** [comment]
I may or may not have got started on this already since it's as good an excuse as any to learn how to work with `ast`. No hard feelings if it doesn't wind up getting merged in. What's the best way to solicit input from other maintainers in the mean time? I don't know the etiquette around tagging people in a situation like this.

**Comment by cooperlees** [comment]
To be fair, the other maintainers are not super active. Ideally we'd give it a week or two then maybe ping. If you have a working unit tested PR, putting that up might help draw more attention.

**Comment by ambv** [comment]
Bugbear is mainly about things that are potentially dangerous. Stylistic changes are under B90x. Put yours there and we'll accept it!

**Comment by joaoe** [comment]
Every time I wrote `not a == b` it was always a bug, like the condition being changed and the `not` just staying there.

**Comment by Zac-HD** [comment]
I'd close this issue; [`flake8-simplify` has `SIM201`](https://pypi.org/project/flake8-simplify/) for exactly this check.

**Comment by cooperlees** [comment]
Thanks for the info @Zac-HD and that's a much better place.
