### ISSUE TITLE
Suggestion: Warnings for left-over `breakpoint()`

### ISSUE THREAD

**Issue by saytosid** [PyCQA/flake8-bugbear#140]
Sometimes this gets slipped through changesets and causes surprises. If the maintainers agree to include this, I'd be happy to help with this 🙂

**Comment by cooperlees** [comment]
I personally feel this is something unit tests should find, not linters.

**Comment by cooperlees** [comment]
Please reopen if you feel otherwise anyone and we can discuss more.

**Comment by saytosid** [comment]
I agree it is something functional and probably best for unit-tests to find. However, I think tests are orthogonal to linter checks. Not all projects have unit tests or good coverage.

So far I have been using [flake8-breakpoint](https://pypi.org/project/flake8-breakpoint/) to warn about `breakpoints()` I think it could be something valuable here as well as this plugin aims to find "likely bugs" which they almost always are.

Upon a brief skim through I can find a few of the existing warnings which can be debated to be more suited for tests than linters IMO. For eg:
> B304: sys.maxint is not a thing on Python 3. Use sys.maxsize.

I would love to hear what people think 🙂 

Re-opening...
