### ISSUE TITLE
`test_does_not_crash_on_any_valid_code` raises hypothesis.errors.FailedHealthCheck in 3.9

### ISSUE THREAD

**Issue by cooperlees** [PyCQA/flake8-bugbear#147]
https://github.com/PyCQA/flake8-bugbear/runs/1444838647
tl;dr
```
hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 7 valid examples in 1.02 seconds (2 invalid ones and 2 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.max_size or max_leaves parameters).
See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.
```

**Comment by cooperlees** [comment]
@Zac-HD - Would love some suggestions here.

I reran the test just to see if it would repro again. It failed on 3.7 this time. Due to this happening on different runtimes, should I add the `too_slow` and move on or do you think there is a found regression here?

I will try and find how I pass this with the `@given` decorator.

**Comment by Zac-HD** [comment]
I'd probably just add `too_slow` and move on - this is probably due to VM contention or something rather than a change in the code.
