### ISSUE TITLE
B015 Pointless comparison advice is not complete

### ISSUE THREAD

**Issue by stevepiercy** [PyCQA/flake8-bugbear#149]
I like this new feature, yet the warning message tells me to do something that I should not do. Also its grammar has a mistake.

> B015 Pointless comparison. This comparison does nothing but wastes CPU instructions. Remove it.

I think it should be:

> B015 Pointless comparison. This comparison does nothing but waste CPU instructions. Either prepend "assert" or remove it.

To verify grammar, remove "nothing but" from "This comparison does nothing but waste" to get the proper verb tense, i.e., "This comparison does waste". Englishing is hard.

See https://github.com/PyCQA/flake8-bugbear/pull/130

**Comment by cooperlees** [comment]
Merged the provided PR. Thanks!

**Comment by stevepiercy** [comment]
Closed by #150.
