### ISSUE TITLE
please keep release names in sync with tags

### ISSUE THREAD

**Issue by ssbarnea** [PyCQA/flake8-bugbear#151]
release name (also listed on project main page) lists: `2020.11.1` but the tag is `20.11.1`, can you please rename the release to match the tag. This could save time when bumping as there is no 2020.11.1 on pypi.

```
stderr:
    ERROR: Could not find a version that satisfies the requirement flake8-bugbear>=2020.11.1 (from versions: 16.4.0, 16.4.2, 16.6.0, 16.6.1, 16.7.0, 16.7.1, 16.9.0, 16.10.0, 16.10.1, 16.11.0, 16.11.1, 16.12.0, 16.12.1, 16.12.2, 17.2.0, 17.3.0, 17.4.0, 17.12.0, 18.2.0, 18.8.0, 19.3.0, 19.8.0, 20.1.0, 20.1.1, 20.1.2, 20.1.3, 20.1.4, 20.11.1)
    ERROR: No matching distribution found for flake8-bugbear>=2020.11.1
```

**Comment by cooperlees** [comment]
Sure. Typos are fun.

How are you hitting this? Installing via GitHub rather than PyPI with pip? What benefits you there? (I’m just interested)

**Comment by pawelad** [comment]
I had a similar 'issue', when I went to GitHub to see the latest release and put `20.3.2` in my requirements. The installation failed because the actual latest release (when going to PyPi page) is `21.3.2`.

**Comment by cooperlees** [comment]
Damn I suck. Will fix today.

**Comment by cooperlees** [comment]
Ok, I think I've fixed this. Will try and be more diligent.

**Comment by pawelad** [comment]
No need for the `terrible maintainer` label! Not what I meant at all, I just wanted to mention the typo as it tripped me a bit.

Thank you for maintaining this library, it's been very helpful to me and countless other people! : -)

**Comment by cooperlees** [comment]
No, thanks for reporting and thanks for sharing that it's been helpful. This was just tongue in cheek poking at myself.
