### ISSUE TITLE
bugbear 21.4.1 + 21.4.2 fails with AttributeError

### ISSUE THREAD

**Issue by xqt** [PyCQA/flake8-bugbear#164]
Newly updated bugbear 21.4.1 fails with AttributeError:
```
21:06:51 Traceback (most recent call last):
21:06:51   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
21:06:51     result = (True, func(*args, **kwds))
21:06:51   File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
21:06:51     return list(map(*args))
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/flake8/checker.py", line 676, in _run_checks
21:06:51     return checker.run_checks()
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/flake8/checker.py", line 589, in run_checks
21:06:51     self.run_ast_checks()
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/flake8/checker.py", line 494, in run_ast_checks
21:06:51     for (line_number, offset, text, _) in runner:
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/bugbear.py", line 36, in run
21:06:51     visitor.visit(self.tree)
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/bugbear.py", line 165, in visit
21:06:51     super().visit(node)
21:06:51   File "/usr/lib/python3.6/ast.py", line 253, in visit
21:06:51     return visitor(node)
21:06:51   File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
21:06:51     self.visit(item)
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/bugbear.py", line 165, in visit
21:06:51     super().visit(node)
21:06:51   File "/usr/lib/python3.6/ast.py", line 253, in visit
21:06:51     return visitor(node)
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/bugbear.py", line 306, in visit_ClassDef
21:06:51     self.generic_visit(node)
21:06:51   File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
21:06:51     self.visit(item)
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/bugbear.py", line 165, in visit
21:06:51     super().visit(node)
21:06:51   File "/usr/lib/python3.6/ast.py", line 253, in visit
21:06:51     return visitor(node)
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/bugbear.py", line 302, in visit_FunctionDef
21:06:51     self.generic_visit(node)
21:06:51   File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
21:06:51     self.visit(item)
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/bugbear.py", line 165, in visit
21:06:51     super().visit(node)
21:06:51   File "/usr/lib/python3.6/ast.py", line 253, in visit
21:06:51     return visitor(node)
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/bugbear.py", line 321, in visit_With
21:06:51     self.check_for_b017(node)
21:06:51   File "/src/.tox/flake8-py36/lib/python3.6/site-packages/bugbear.py", line 442, in check_for_b017
21:06:51     hasattr(item_context.func, "attr")
21:06:51 AttributeError: 'Name' object has no attribute 'func'
21:06:51 """
```
See https://integration.wikimedia.org/ci/job/pywikibot-core-tox-docker/14952/console

**Comment by mraspaud** [comment]
Same here, was just filing an issue myself:

We have automating lint checks with flake8 with bugbear running and it looks like the latest release from about an hour ago broke something. Here is what we are getting now
https://github.com/pytroll/satpy/pull/1628/checks?check_run_id=2248802984#step:6:23

 AttributeError: 'Name' object has no attribute 'func'

Was running fine until then.

We are calling this with:
https://github.com/pytroll/satpy/blob/master/.github/workflows/ci.yaml#L25

Or are we doing something wrong?

Thanks
cc @djhoese

**Comment by cooperlees** [comment]
No, this seems like a bug we will need to repro with tests and fix.

Two workarounds are:
- roll back to 21.3.2
- disable B017 in flake8 conf

I will try find cycles tonight, but my day is very busy. PR welcome.

**Comment by cricalix** [comment]
@xqt - could you give me a sample line of code that this is breaking on? I'm thinking I can fix with a ``hasattr(item_context, "func")`` in the if block, but it'd be good to have some more negative test cases to ensure I'm catching everything correctly.

**Comment by cooperlees** [comment]
Please test with #165 - There might be more edge cases but I think this will get it.

**Comment by cooperlees** [comment]
21.4.2 released. Will yank 21.4.1 from PyPI.

**Comment by cooperlees** [comment]
@ambv - Can you please yank 21.4.1, I don't have access.

**Comment by DStape** [comment]
Unfortunately with 21.4.2 I still experience: ```AttributeError: 'Attribute' object has no attribute 'id'``` (was ```AttributeError: 'Attribute' object has no attribute 'func'``` in 21.4.1).

**Comment by cooperlees** [comment]
We need some code examples please to add to the unit test code to ensure.

Please pin to old version for now. I’d ya k the versions but I can’t. My express release didn’t help. Sorry. Going to need more conditions.

**Comment by cricalix** [comment]
Hmm. Naive approach that's the fastest fix is possibly to put a try block on that whole set of code, and let it silently fail. Not the nicest way though.

The error you're getting says that you've got a line of code that triggers as being a function, having the attr attribute in the AST node for the Call, the attr is assertRaises, there's one argument (I was deliberately avoiding assertRaises(Exception, Bob)), and yet whatever that AST node is, it doesn't have an id attribute.

Do you have code that does something like self.assertRaises("string") @DStape ?

**Comment by cooperlees** [comment]
Since i can't yank I'd like to forward fix or do something crude to stop people's CI dying all over the world ...

**Comment by cricalix** [comment]
I have a somewhat forward fix about to go up, but I really can't tell if I'm fixing all the cases of the problem. Adding another condition to the tree walk to check the type of element for args[0].

**Comment by DStape** [comment]
@cooperlees, @cricalix , here's a stripped down example of code bugbear is error-ing out on for us:
```
import asyncio
 from unittest import TestCase
 
 
 class Foo:
     def __init__(self):
         raise NotImplementedError
 
 
 class TestFoo(TestCase):
     def test_(self):
         with self.assertRaises(asyncio.CancelledError):
         #from asyncio import CancelledError  # no AttributeError
         #with self.assertRaises(CancelledError):
             Foo()
```

Note that when ```CancelledError``` is imported from ```asyncio```, the ```AttributeError``` does not occur.

**Comment by cricalix** [comment]
Ok, test case added, and confirms that my in-flight fix fixes that case. I'll have to walk the AST tree to get a better feel for what your syntax is doing, but it looks like there's another layer of nesting in that case.

**Comment by cricalix** [comment]
K, #166 is up for review.

**Comment by cricalix** [comment]
And yeah, it's a messy set of stuff in the merge; I haven't used git for several years now, and it shows. I can drop my fork and re-do the submission if needed.

**Comment by xqt** [comment]
> 
> 
> @xqt - could you give me a sample line of code that this is breaking on? I'm thinking I can fix with a `hasattr(item_context, "func")` in the if block, but it'd be good to have some more negative test cases to ensure I'm catching everything correctly.

Difficult to give a code sample, our framework has 50.000 LOC. All I can say is that our tests passes with Python 3.5.7 but failed due to this issue with Python 3.6.9. There is one difference: Python 3.6 tests require mwparserfromhell and bs4 to be installed.

**Comment by csdev** [comment]
21.4.3 works for me now. (21.4.1 was broken for me even though I don't use `unittest.assertRaises` -- I use `pytest.raises` on Python 3.7.9.)
However, if other users are still experiencing problems, perhaps you can make B017 an opt-in feature like B9xx until it is more stable?

**Comment by mraspaud** [comment]
Works for me too. Thanks for the fix!
