### ISSUE TITLE
Extend B017 to pytest.raises

### ISSUE THREAD

**Issue by tsx** [PyCQA/flake8-bugbear#169]
`with pytest.raises(Exception):` is very similar to `assertRaises`, and all the justification of B017 applies to that too.

**Comment by cooperlees** [comment]
Sounds reasonable. Unit-tested adding to B017 will be merged.

**Comment by AbdealiLoKo** [comment]
I have a case where I use:
```
with pytest.raises(Exception, reason='Parsing error'):
    call_my_func()
```

Currently, B017 catches this as a problematic but I have a  valis `reason` here which catches a very specific error message

**Comment by cooperlees** [comment]
I still feel it's a good practice to subclass Exception here too ...

**Comment by Dreamsorcerer** [comment]
The error currently says `Either assert for a more specific exception (builtin or custom), use assertRaisesRegex, or use the context manager form of assertRaises.`

Which I assume refers to the unittest functions. But, it'd be weird to suggest using assertRaisesRegex() and then say that `match` is not allowed.

**Comment by mrcljx** [comment]
> I have a case where I use:
> 
> ```
> with pytest.raises(Exception, match='Parsing error'):
>     call_my_func()
> ```
> 
> Currently, B017 catches this as a problematic but I have a valid `match` here which catches a very specific error message

@AbdealiLoKo As a workaround, you can use https://github.com/m-burst/flake8-pytest-style/blob/master/docs/rules/PT011.md to catch that.

**Comment by AbdealiLoKo** [comment]
Sure thanks @mrcljx will take a look.

**Comment by Dreamsorcerer** [comment]
Appears this has been resolved (probably someone forgot the 'fixes' in a PR?).

**Comment by cooperlees** [comment]
Yup. This is all done. Thanks for the nudge.

**Comment by cooperlees** [comment]
FWIW - I dislike using `assertRaisesRegex` too, just make a custom exception type. I do accept there are edge cases where you're testing something you can't easily change etc. etc.
