### ISSUE TITLE
AttributeError: 'Call' object has no attribute 'value'

### ISSUE THREAD

**Issue by jaap3** [PyCQA/flake8-bugbear#171]
I added flake8-bugbear to a project that could use some cleanup, but upon running flake8 it crashed with a `AttributeError: 'Call' object has no attribute 'value'`.

I boiled down the offending code to this reproducer:

```python
from django.contrib.auth import get_user_model


def get_user_by_email(email):
    try:
        return get_user_model().get(email=email)
    except (
        get_user_model().DoesNotExist,
        get_user_model().MultipleObjectsReturned
    ):
        pass
```

This is with the following version of flake8/plugins/python:

```
flake8 --version
3.9.2 (flake8-bugbear: 21.4.3, mccabe: 0.6.1, pycodestyle: 2.7.0, pyflakes:
2.3.1) CPython 3.7.10 on Linux
```

**Comment by szabgab** [comment]
I got the same error when I tried to run flake8 with bugbear installed on the source code of https://github.com/ansible/ansible

**Comment by jaap3** [comment]
Here's the shortest reproducer I can come up with that generates the same stacktrace :

```
foo = lambda: IOError

try:
    ...
except (foo(),):
    ...
```

**Comment by jaap3** [comment]
This is now fixed

**Comment by szabgab** [comment]
Thank you. I just checked and the most recent version (21.9.2) does not raise an exception on the source code of ansible.

**Comment by cooperlees** [comment]
Awesome. Thanks for report/confirming the fix worked!
