### ISSUE TITLE
B014: binascii.Error and ValueError redundancy not caught

### ISSUE THREAD

**Issue by Haganeno** [PyCQA/flake8-bugbear#178]
I found an issue with flake8 not raising any flags for the following code:
```
try:
   ...
except (ValueError, binascii.Error):
    pass
```

whereas the error ```B014 Redundant exception types in `except (ValueError, UnicodeDecodeError):`.  Write `except ValueError:`, which catches exactly the same exceptions.``` is raised for the code below:
```
try:
   ...
except (ValueError, UnicodeDecodeError):
    pass
```

I find it strange as both `UnicodeDecodeError` and `binascii.Error` both inherit from `ValueError`

Is it a known issue?

**Comment by cooperlees** [comment]
Hi,

Thanks for reporting. This is not a known issue. A fix PR is more than welcome if someone can workout the root cause.

Cheers
