### ISSUE TITLE
Proposed check: explicit `raise` in `except` or `finally` should use `from ...`

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/flake8-bugbear#180]
Thanks to [PEP 3134](https://www.python.org/dev/peps/pep-3134/), Python 3 supports [exception chaining](https://docs.python.org/3/tutorial/errors.html#exception-chaining).  For example,

```python
try:
    assert False
except AssertionError as err:
    raise RuntimeError("An assertion failed")  # Should use `from err` or `from None`
```
```python-traceback
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    assert False
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t.py", line 4, in <module>
    raise RuntimeError("An assertion failed")
RuntimeError: An assertion failed
```

The line `During handling of the above exception, another exception occurred:` is not strictly speaking *wrong*, but for explicit `raise` statements we can do better:

- If we want to *replace* the earlier exception, we should `raise ... from None` to omit it from the traceback
- If we want to *add more information*, we should `raise ... from err` - the message would then be `The above exception was the direct cause of the following exception:`

*This issue was prompted by reading https://github.com/numpy/numpy/issues/15986 and wishing for a better tool than `grep` to check my own code.*

**Comment by cooperlees** [comment]
Yeah I like this. It is a lot clearer (I've never done this ... so thanks for exposing me to this ability). 

I'd accept this check - so unless another maintainer clearer shares a reason not to seems good.

Just remember:
- Tests
- Docs (in README)

Thanks!
