### ISSUE TITLE
Suggestion: Forbid function/method calls in except statement

### ISSUE THREAD

**Issue by jaap3** [PyCQA/flake8-bugbear#192]
Recently I "fixed" issue #171 (by which I mean, let bugbear not crash when encountering function calls in a except statement). But maybe that pattern shouldn't be allowed at all?

E.g. it's not possible for bugbear to enforce B013 or B014 if the return value of the call is not determined, which means that the following code is currently "fine" according to bugbear:

```
def foo():
    return (Exception,)


try:
    ...
except foo():
    ...
```

```
def bar():
    return (LookupError, KeyError, IndexError)


try:
    ...
except bar():
    ...
```

**Comment by Zac-HD** [comment]
There are also [cases like `anyio.get_cancelled_exc_class()`](https://anyio.readthedocs.io/en/stable/api.html#anyio.get_cancelled_exc_class), so I don't think banning such calls is feasible.
