### ISSUE TITLE
Bugbear and builtins both using B001

### ISSUE THREAD

**Issue by cas--** [PyCQA/flake8-bugbear#20]
I have not tested the consequences of this but I found googling for B001 that you both picked the same B prefix code in March 2016!

https://github.com/gforcada/flake8-builtins

**Comment by 153957** [comment]
Where does builtins use a Bxxx error code? I only see 3 codes, named `A00[1-3]`:
https://github.com/gforcada/flake8-builtins/blob/master/flake8_builtins.py#L39-L44

**Comment by cas--** [comment]
The commit and blame history for those lines is a clue...

https://github.com/gforcada/flake8-builtins/issues/7
