### ISSUE TITLE
B018 complains about f-strings as docstrings... and it's right!  (but a more specific message would be helpful)

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/flake8-bugbear#211]
```python
CONSTANT = "magic value"

def f():
    f"""Return {CONSTANT!r}."""  # warning B018
    return CONSTANT

assert f.__doc__ is not None  # fails!
```

I was originally reporting this as a bug, but it turns out that f-strings don't work as docstrings!  IMO this deserves to be split out into a new B019 check with a more specific message.

**Comment by cooperlees** [comment]
Nice. Would totally accept this PR if we can cleanly split this error out. 

First, we need to workout our long term design with string detection in general for `B018` as #208 has identified from the abstract use case sphinx uses and I am sure other edge cases will come up.
