### ISSUE TITLE
Proposed Check: same variable name of list and interating item in for-loop

### ISSUE THREAD

**Issue by rosaldo260** [PyCQA/flake8-bugbear#219]
I've already placed a question [here](https://stackoverflow.com/questions/70827394/is-there-pep-rule-or-pre-commit-check-to-prevent-same-name-of-variable-and-list). Then found this project.

```
items = [1, 2, 3]
for items in items:
    continue
# items == 3
```
This typo accidentally happened to me and caused a bug.  
Would be nice to catch it with something like: `Bxxx for-loop with the same variable name of the list and interating item found.`

**Comment by cooperlees** [comment]
Hi, thanks for bringing up this proposal. 

I am a fan of this check, but, I'm torn here with adding this check as some people do (and I dislike it and personally always comment for change in reviews) use in loop variables outside the loop once complete. I do think this check adds value as the variable name **should** always be different, as a common thing in python is to iterate the plural meaning iterable and assign each value to the singular term as the variable name. For Example:

```python
colours = ['green', 'blue']
for colour in colours:
  a_colour = colour
print(a_colour)  # also evil in ways and hard to find sometimes when bugs arise ...
```

This check would help highlight this potential bug, so for me, I'd accept a check for this with unit tests and an addition to the Change Log. But please speak up if you dislike this for any reason.

The main thing I see here hard to debug is the loop works as desired. Here I tested the example code to show others the potential bug in more verbose detail:

```python
items = [1, 2, 3]
for items in items:
    print(f"LOOP: {items}")
    continue
print(f"After Loop items: {items}")
```
Output:
```
[cooper:~]$ python3 /tmp/silly.py
LOOP: 1
LOOP: 2
LOOP: 3
After Loop items: 3  # Not the list anymore
```

**Comment by rosaldo260** [comment]
BTW for now am using this regex `([_A-Za-z][A-Za-z0-9]*)\s+in\s+\1\b` to check for such occurance. Might help...   
But this one does not catch the following case because of `, value` between:  
```
key = {"secret": 123}
for key, value in key.items():
    print(f"{key=}, {value=}"
```

**Comment by Korben11** [comment]
```
colours = ['green', 'blue']
for colour in colours:
  a_colour = colour
print(a_colour)  # also evil in ways and hard to find sometimes when bugs arise ...
```
PyCharm IDE warns me about **"Name 'a_colour' can be undefined"**
Found that it's not catched by **pylint**, but **pylint-pycharm** [extension](https://www.jetbrains.com/help/pycharm/command-line-code-inspector.html#inspection-profiles) which probably not usable in pipeline.   

Didn't find any other check that would catch it, so would be nice to add it as well.
