### ISSUE TITLE
Proposed Check: use of blocking HTTP requests in async functions

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/flake8-bugbear#225]
During some cleanup at work, I found an `async` function which internally called `httpx.get()`... and therefore blocked waiting for IO 😭.  

To check for other such cases I put together a tiny little plugin, and I'm keen to upstream it - whether here (though #159 suggests maybe not), in another package, or in a new package (though it'll be abandonware if so).  So, thoughts?  Suggestions for where this should live?

```python
import ast
from itertools import chain

MSG = "HX100: sync HTTP call in async function should use httpx.AsyncClient"
PACKAGES = ("requests", "httpx")
METHODS = "get options head post put patch delete request send".split()


class Visitor(ast.NodeVisitor):
    def __init__(self) -> None:
        super().__init__()
        self.errors = []  # list of (lineno, colno, message)

    def visit_AsyncFunctionDef(self, node):
        for inner_node in chain.from_iterable(map(ast.iter_child_nodes, node.body)):
            if (
                isinstance(inner_node, ast.Call)
                and isinstance(inner_node.func, ast.Attribute)
                and isinstance(inner_node.func.value, ast.Name)
                and inner_node.func.value.id in PACKAGES
                and inner_node.func.attr in METHODS
            ):
                self.errors.append((inner_node.lineno, inner_node.col_offset, MSG))
        self.generic_visit(node)


class Plugin:
    name = __name__
    version = "0.0.0"

    def __init__(self, tree: ast.AST) -> None:
        self.tree = tree

    def run(self):
        visitor = Visitor()
        visitor.visit(self.tree)
        for line, col, msg in visitor.errors:
            yield (line, col, msg, type(self))
```
```python
import ast
import pytest
from flake8_httpx import MSG, Plugin

@pytest.mark.parametrize(
    "s,err",
    [
        ("", set()),
        ("def f():\n    httpx.get('')\n", set()),
        (
            "async def f():\n    httpx.get('')\n",
            {(2, 4, MSG, Plugin)},
        ),
    ],
)
def test_expected_results(s, err):
    assert set(Plugin(ast.parse(s)).run()) == err
```
```python
    # in setup.py
    entry_points={
        "flake8.extension": [
            "HX = belt.flake8_httpx:Plugin",
        ],
    },
```

**Comment by cooperlees** [comment]
Hey Zac,

Since we now have two requests for async check, want to co-start a flake8-async / flake8-asyncio plugin to check for everything async related? We can start off in one of our GitHub accounts and if it gets popular maybe move it here.

This plugin could focus looking for sync calls in async coroutines and non awaited async coros etc. could be useful. I just haven't looked at how good the ast/maybe the PEG parser could be used to make this?

Thoughts there?

**Comment by Zac-HD** [comment]
Sounds good - if you're up for starting it, I'm happy to open a PR with this and also my usual tox checks + autorelease setup if you want it 🙂

**Comment by cooperlees** [comment]
Ok - I'll try get a blank repo the next few days and we can kick it off.

**Comment by Zac-HD** [comment]
Closed by https://github.com/cooperlees/flake8-async/pull/1
