### ISSUE TITLE
BUG/QUESTION: Not sure if B020 is expected to trigger here

### ISSUE THREAD

**Issue by neutrinoceros** [PyCQA/flake8-bugbear#235]
running flake8 with the latest version of bugbear on this snippet
```python
for var in (var for var in range(10) if var % 2):
    print(var)
```
results in
```
t.py:1:5: B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
```
Is this expected ? I don't understand how the error message relates to what's actually happening here, it seems to me that this could be a mistake.

**Comment by cooperlees** [comment]
Thanks for reporting. This is definitely an edge case I feel we'd want to handle and ignore.

The goal is to ensure we don't re-assign the iterable the for loop is iterating. Maybe we need an example in the error message too.

**Comment by Korben11** [comment]
I agree we should ignore this edge case. Following will skip generator expressions from the check.
```py
        if isinstance(node.iter, ast.GeneratorExp):
            return None
```
Also found out that the generator doesn't override variables from the outer scope.

I can create a pull request if u agree with the solution.

**Comment by jpy-git** [comment]
It's comprehensions in general not just generators
```
for var in [var for var in range(10)]:
    print(var)

for var in (var for var in range(10)):
    print(var)

for k, v in {k: v for k, v in zip(range(10), range(10, 20))}.items():
    print(k, v)
```

**Comment by cooperlees** [comment]
Totally a PR adding new test cases for all cases discussed here and showing correct flake8 behavior will totally be accepted. Thanks all!

**Comment by jpy-git** [comment]
I've made a PR to these false positives 👍

**Comment by jenstroeger** [comment]
Not sure if I should open a new issue or if this case just isn’t that important (simplified example):
```python
for text in (s for s in text.splitlines(keepends=True)):
    ...
```
Considering that [str.splitlines()](https://docs.python.org/3/library/stdtypes.html#str.splitlines) returns a list I would argue that this snippet is safe. Easy to fix though by changing the variable names.
