### ISSUE TITLE
False positive for B019

### ISSUE THREAD

**Issue by neriusmika** [PyCQA/flake8-bugbear#236]
After the latest update, there are false positives for B019 on regular methods:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/23192030/159234041-8e8de5ac-6818-4d28-8ae6-08baf9b1da96.png">

**Comment by jpy-git** [comment]
The lint is working correctly:
https://github.com/PyCQA/flake8-bugbear/blob/0069532182d78ac0a41de94aab8d71db2398de2d/tests/b019.py#L72-L103

Here's a great [video](https://www.youtube.com/watch?v=sVjtp6tGo0g) on why this is advised against 😄 

IMO the lint message is very misleading though. it says `class methods` meaning `methods on a class` (which is pretty much the definition of a `method`) and probably leads to confusion with `classmethods` which have a very specific meaning. Will update the lint description to make it clearer 👍

**Comment by neriusmika** [comment]
Actually, I don't have this problem in my code, because the class itself is a singleton. Thank you for description clarification. At least it will not be confusing why it's ignored.
