### ISSUE TITLE
Add autoupdate pre-commit

### ISSUE THREAD

**Issue by cooperlees** [PyCQA/flake8-bugbear#240]
Add auto updating of our pre-commit config

**Comment by jpy-git** [comment]
Looks like there's a github action we could use to automatically create a PR for us: https://github.com/marketplace/actions/pre-commit-autoupdate

**Comment by sco1** [comment]
There is also https://pre-commit.ci/

**Comment by cooperlees** [comment]
> There is also https://pre-commit.ci/

This was the one - I clicked things. I think we have it now ...

**Comment by sco1** [comment]
Should be good to go! Autoupdate usually runs on Mondays at 1600 UTC & will open a PR if there are any changes.

**Comment by jpy-git** [comment]
Nice! 😎
