### ISSUE TITLE
B008 regression: lambdas

### ISSUE THREAD

**Issue by Dreamsorcerer** [PyCQA/flake8-bugbear#244]
The last update flags this up as a warning now: https://github.com/aio-libs/aiohttp-session/blob/dependabot/pip/flake8-bugbear-22.3.23/aiohttp_session/redis_storage.py#L30

`key_factory: Callable[[], str] = lambda: uuid.uuid4().hex,`

But, actually, there is no function call in the default, it is just defining a lambda.

**Comment by jpy-git** [comment]
Hi @Dreamsorcerer, this is a dupe of #242 which we fixed yesterday and will be in the next release 👍

**Comment by Dreamsorcerer** [comment]
Thanks, missed that.
