### ISSUE TITLE
Multi-inheritance B024

### ISSUE THREAD

**Issue by barney-ellis** [PyCQA/flake8-bugbear#277]
Hi, 

The latest release introduced a new error code (B024) which checks that an abc defines abstract methods/properties. I have an abc, `A`, which has a `__call__` abstract method. 

    class A(metaclass=abc.ABCMeta):
  
      def __eq__(self, other: Any) -> bool:
          ...
  
      def __repr__(self) -> str:
          ...
  
      @abc.abstractmethod
      def __call__(self, ...) -> ...:
          raise NotImplementedError`

I also have a different abc, `RandomA` which shares `A`'s methods (such as `eq`) and abstract `__call__`, but also has a random number generator as an instance variable

    class RandomA(A, metaclass=abc.ABCMeta): 
  
        def __init__(self, rng: Optional[np.random.Generator]) -> None:
            self.rng = rng if rng is not None else np.random.default_rng()

This way I can create child classes which have deterministic or random behaviour. 

`RandomA` now violates B024 as it doesn't define abstract methods, even though it should inherit `A`'s `__call__` method right?

**Comment by Zac-HD** [comment]
Yep, that's a false alarm.

I think in this specific case you don't need to declare the metaclass though, since that should be inherited from `A`?  I could be wrong though.

**Comment by barney-ellis** [comment]
This passes the flake8 tests, however my IDE (PyCharm) flags a warning that I'm not implementing `call` from `A`

**Comment by Zac-HD** [comment]
Hmm, I think Pycharm is also giving a false alarm there!

Nonetheless, we've got something to fix too. I propose that B024 be disabled for child classes which inherit from anything but abc.ABC - it'll miss some warnings, but still cover the common cases.

**Comment by jakkdl** [comment]
Yeah that sounds good, and also fixes #278
