### ISSUE TITLE
Proposed check: don't allow argument unpacking in a call after a keyword argument

### ISSUE THREAD

**Issue by pmeier** [PyCQA/flake8-bugbear#286]
Imagine a function like

```py
def foo(bar, baz):
    pass
```

The following call is a syntactically incorrect:

```py
foo(baz="baz", "bar")
```

However, with unpacking the following is allowed:

```py
foo(baz="baz", *["bar"])
```

[However](https://github.com/python/cpython/issues/82741#issuecomment-1093845041),

> [T]he resulting argument binding is awkward, and almost never does what you want/expect it to

It was [not ruled a bug or a behavior that can or should be deprecated](https://github.com/python/cpython/issues/82741#issuecomment-1093845049). Still, I think in most cases this is probably an oversight and should not be used.

If we want this check, I would be willing to contribute a patch.

**Comment by cooperlees** [comment]
Howdy - Agree this is an anti pattern I don't want in my code so I'm +1 on this check being added.
