### ISSUE TITLE
Require warnings.warn stacklevel argument as 2+

### ISSUE THREAD

**Issue by adamchainz** [PyCQA/flake8-bugbear#299]
Calling [`warnings.warn()`](https://docs.python.org/3/library/warnings.html#warnings.warn) without a `stacklevel`, or a `stacklevel` value of <2, is nearly always a mistake. Doing so flags the warning inside the called function, rather than the caller, making it hard to fix the warning.

flake8-bugbear could detect such invocations of `warnings.warn()`.

This issue inspired by @asottile's video of the day: https://www.youtube.com/watch?v=CtFdXBEwYfk . This is also something I've seen recur as a review point in Django PR's.

**Comment by cooperlees** [comment]
Sounds a good one to me for bugbear to check.

I would accept a PR with unit tests showing this working. Please remember to add a verbose description to README too.
