### ISSUE TITLE
Fix tox for python3.11 and future new versions

### ISSUE THREAD

**Issue by cooperlees** [PyCQA/flake8-bugbear#300]
tox isn't doing anything useful in 3.11 CI. Example: https://github.com/PyCQA/flake8-bugbear/actions/runs/3316961501/jobs/5479325116#step:5:41

```console
Run tox
  tox
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.0-rc.[2](https://github.com/PyCQA/flake8-bugbear/actions/runs/3316961501/jobs/5479325116#step:6:2)/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.0-rc.2/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.0-rc.2/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.0-rc.2/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib
Warning: WARNING: tox-gh-actions couldn't find environments matching the provided factors from envlist. Please use `tox -vv` to get more detailed logs.
___________________________________ summary ____________________________________
  congratulations :)
```

Need to workout how to fix as I'm no tox guru. Help would be appreciated.

**Comment by inwaves** [comment]
Hi! I just took a look at this. I think it's related to how `tox-gh-actions` parses the Python versions specified under `[gh-actions]`. As far as I can tell, it's only considering `major.minor`, which doesn't match our request for `major.minor.micro-releaselevel`. There are two options here:
- in the short term, we can change the version string to `3.11: py311`. See this [CI run](https://github.com/inwaves/flake8-bugbear/actions/runs/3635956234/jobs/6135511669#step:6:14) for confirmation.
- in the long term, we should try to get a PR in upstream so we can use release ranges and extended syntax, as spcified [here](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-input).

**Comment by inwaves** [comment]
Hm, I wonder if getting rid of the plugin is causing more trouble than leaving it in for now, and updating the 3.11 to just 3.11 (instead of rc). We might be able to get a change in upstream before 3.12.

I've looked around a bit and it seems as though `tox-gh-actions` is the one properly matching the environment options in `tox.ini` to the Python versions in `ci.yml`. I'm not sure why without this plugin `tox` matches py310 before it matches py311. I've looked around for references to fuzzy matching in envlist, but nothing turned up.

**Comment by inwaves** [comment]
Checked back in upstream on tox-gh-actions issue [#132](https://github.com/ymyzk/tox-gh-actions/issues/132). It looks like we should be able to leave that on, specify the release candidate version in our workflow YAML, and then just specify it using a "shorthand" version in `tox.ini` (i.e. in our case, 3.11/3.12 would get matched to a release candidate if that's what we provided in the YAML).
