### ISSUE TITLE
Opinionated warning: require `strict=` argument to `zip()` builtin

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/flake8-bugbear#311]
In Python 3.10, [PEP-618 added optional length-checking to `zip()`](https://peps.python.org/pep-0618/).

Requiring uses of `zip()` to declare either `strict=` would be a nice option to prevent bugs when the argument was omitted, and the iterables were unexpectedly of different lengths.  Of course it could also be pretty noisy, not to mention requiring Python 3.10 or later, so I think this should be disabled by default.

**Comment by cooperlees** [comment]
Sounds helpful and worth adding. I for one didn't know this was added. Could we not just enable it only for >= 3.10 by default and not for < 3.10?

**Comment by Zac-HD** [comment]
I don't think we can (consistently) tell what the intended my minimum Python version should be, so enabled by default doesn't seem practical until 3.9 reaches end of life.
