### ISSUE TITLE
Report incorrect assigning of dictionary entries with a colon (`:`)

### ISSUE THREAD

**Issue by dannysepler** [PyCQA/flake8-bugbear#312]
Consider the following code

```python
dct = {
    'a': 1,
}
dct['b']: 2
print(dct)  # {'a': 1}
```

This is actually valid python syntax, because it is typing the 'b' entry as a 2 type. But we can assume the user meant to assign an element rather than type it (especially if there's no equal on this line).

(Recommended I post this to `bugbear` by `pyflakes` maintainers here: https://github.com/PyCQA/pyflakes/issues/756)

**Comment by cooperlees** [comment]
Nice catch. Agree this is perfect for bugbear, as long as we can get it accurate like @asottile mention on the pyflakes issue. Lets have tests prove that.
