### ISSUE TITLE
Crash on nested tuple in except handler

### ISSUE THREAD

**Issue by JelleZijlstra** [PyCQA/flake8-bugbear#345]
Run flake8-bugbear on this file:
```python
try: x
except (a, (b, c)): pass
```

And you will get a stack trace that ends with

```
  File "/Users/jelle/py/venvs/py311/lib/python3.11/site-packages/bugbear.py", line 283, in visit_ExceptHandler
    names = [_to_name_str(e) for e in node.type.elts]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jelle/py/venvs/py311/lib/python3.11/site-packages/bugbear.py", line 283, in <listcomp>
    names = [_to_name_str(e) for e in node.type.elts]
             ^^^^^^^^^^^^^^^
  File "/Users/jelle/py/venvs/py311/lib/python3.11/site-packages/bugbear.py", line 202, in _to_name_str
    return _to_name_str(node.value)
                        ^^^^^^^^^^
AttributeError: 'Tuple' object has no attribute 'value'
```

Why would you use nested tuples in except handlers, you may ask. I'm not sure, but it's legal syntax so I am testing it in the [pyanalyze](/quora/pyanalyze) test suite.

**Comment by cooperlees** [comment]
Thanks Jelle for reporting. I think flake8 plugins shouldn't crash on what cpython deems valid syntax, no matter how wrong it is. Lets try not crash here.

**Comment by JelleZijlstra** [comment]
> This wouldn't do anything functional would it?

Not in my example because the names are undefined, but in general it's equivalent to the unnested tuple. So if you do `except (TypeError, (ValueError, (RuntimeError, KeyError)))`, you catch all of those errors. I don't think bugbear should lint against this since it's valid code that does what I'd expect, it's just ugly.

**Comment by JelleZijlstra** [comment]
Though bugbear also crashes on things like `except (3,):`. We could probably lint against anything in an except handler that's not a tuple, Attribute, or Name.
