### ISSUE TITLE
B030 doesn't allow splatted exceptions

### ISSUE THREAD

**Issue by samueljsb** [PyCQA/flake8-bugbear#352]
I *think* there's a false-report coming from B030 where we have some exceptions types defined in a constant. A minimal example:

```python
EXCEPTIONS_TO_IGNORE = (
    ValueError,
    TypeError,
)

try:
    pass
except (SyntaxError, *EXCEPTIONS_TO_IGNORE):
    pass
```

```console
$ flake8 t.py
t.py:8:1: B030 Except handlers should only be names of exception classes
```

This isn't incorrect, so I don't *think* the intention of B030 is to stop this kind of thing. 

<details>
<summary>versions etc</summary>

I'm using Macos 13.1, we're also seeing this in CI using Ubuntu 20.04.5.

```console
$ python --version --version
Python 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]

$ flake8 --version
6.0.0 (flake8-bugbear: 23.2.13, mccabe: 0.7.0, pycodestyle: 2.10.0, pyflakes: 3.0.1) CPython 3.10.8 on Darwin
```

</details>

**Comment by samueljsb** [comment]
It also doesn't allow function calls:

```python
def exceptions_to_ignore():
    return (ValueError, TypeError)

try:
    pass
except exceptions_to_ignore():
    pass
```

```console
$ flake8 t.py
t.py:6:1: B030 Except handlers should only be names of exception classes
```

Whether or not this is a good way to write code or not is an open question, but should it be disallowed?

**Comment by jakkdl** [comment]
https://github.com/PyCQA/flake8-bugbear/blob/fa49539b05e2f1c0962ff3d09a86a889b16b9c92/bugbear.py#L336-L340
is the current logic.
Starred expressions seems reasonable to allow, and function calls are probably intentional too? But feels like there's not a ton left for the error to catch after that, the test currently just tests constants. https://github.com/PyCQA/flake8-bugbear/blob/main/tests/b030.py

**Comment by JelleZijlstra** [comment]
We should definitely allow splats, I'll send a PR. We discussed this a bit on #346 and landed on disallowing them, but if there's real use cases where people use calls, we can revisit that decision.

**Comment by samueljsb** [comment]
To be clear, the function call happened once in our 35k-module codebase -- I've refactored it to assign the returned set of exceptions to a variable and it's now much clearer what's going on so please don't take this as a vote to allow function calls from me!
