### ISSUE TITLE
Warn on `except A | B:`, which is a runtime error

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/flake8-bugbear#363]
```python
t = ZeroDivisionError | ValueError           # Python 3.10 syntax for types.UnionType
assert isinstance(ZeroDivisionError(), t)    # isinstance and issubclass work

try: 
    1/0
except ZeroDivisionError | ValueError as e:  # but this fails!
    print(e)
```
```python-traceback
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    1/0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    except ZeroDivisionError | ValueError as e: 
TypeError: catching classes that do not inherit from BaseException is not allowed
```

I think we should have a lint warning for this, since I've seen it bite in the wild and [it will remain an error going forward](https://github.com/python/cpython/issues/102414).

**Comment by JelleZijlstra** [comment]
I think I already made this happen: `test.py:3:1: B030 Except handlers should only be names of exception classes`.

**Comment by Zac-HD** [comment]
It does, but only as an optional warning - I think the `|` syntax is specifically likely enough to be used - since it can be in `isinstance()` and `issubclass(()` - and then error that we should consider enabling a narrow version of the check by default.

**Comment by Zac-HD** [comment]
🤦‍♂️ just needed to update to the latest version, yep.  Cheers Jelle!
