### ISSUE TITLE
Move to >= 3.8.1 like flake8 + maybe add a CI check somehow

### ISSUE THREAD

**Issue by cooperlees** [PyCQA/flake8-bugbear#365]
Bonus: Maybe add some CI to check if our python-requires matches flake8

We could request that latest simple page for each project (i.e. https://pypi.org/simple/flake8/ and https://pypi.org/simple/flake8-bugbear/) and compare the latest version's `data-requires-python`
- There is even a JSON version of these pages now ...

I think weekly would be enough to run the check

**Comment by FozzieHi** [comment]
Are there any major blockers to this update?

There's some minor ones which ideally we'd want to change, for example there's quite a few deprecated ast methods since 3.8 such as `visit_Num()`, `visit_Str()`, `visit_Bytes()`, `visit_NameConstant()`, `visit_Ellipsis()` having all been replaced with `visit_Constant()`.

**Comment by cooperlees** [comment]
> Are there any major blockers to this update?

Na, just need to start doing it and use pyup and move tooling to be >= 3.8 so we can move the code base forward.

> There's some minor things that ideally we'd want to change. For example, there's quite a few deprecated ast methods since 3.8 such as `visit_Num()`, `visit_Str()`, `visit_Bytes()`, `visit_NameConstant()`, `visit_Ellipsis()` having all been replaced with `visit_Constant()`.

Yup, we should take advantage of all the AST improvements. Any TODO's or comments that state we can update things too ...

All PRs welcome, small or large to get us there.

**Comment by FozzieHi** [comment]
Yup, happy to submit a PR with what I mentioned above. Do you want to create a `3.8` branch or something similar, or do you want this straight into `main`?

**Comment by cooperlees** [comment]
> Yup, happy to submit a PR with what I mentioned above. Do you want to create a `3.8` branch or something similar, or do you want this straight into `main`?

Happy to go to main and make next release >=3.8 ...

**Comment by FozzieHi** [comment]
@cooperlees I think we've pretty much covered everything? We might want to change the `flake8` dependency requirement from `>=3.0.0` to `>=6.0.0` like I briefly mentioned in #368.

Not sure how a CI check would work, or if it's really needed given how infrequently the versions change.

**Comment by cooperlees** [comment]
Yeah, I agree, the CI can wait, but I want to check if we match base flake8 better in the long run.

I agree with the >=6.0.0 flake8. Will try get to it or PR welcome and I'll get a release out as soon as we are as we also have a bug fix we need to get out ...

I might make a periodic action one day to check for this ...
