### ISSUE TITLE
New check finding easteregg imports

### ISSUE THREAD

**Issue by kasium** [PyCQA/flake8-bugbear#377]
Python has some easter egg modules: `this`, `antigravity`, `__hello__` and `__phello__`. There also easteggs in `__future__` called `braces` and `barry_as_FLUFL`. I guess a simple check finding these in `ast.Import` and `ast.ImportFrom` doesn't hurt.

I'm happy to contribute these checks

**Comment by JelleZijlstra** [comment]
How would this contribute to this project's purpose of finding bugs? It feels unlikely that people would add this import and need a linter to tell them to remove the import.

**Comment by kasium** [comment]
@JelleZijlstra I guess B010, B013 and B9x are also flagging non-bugs but best practices. I'm fine not seeing these checks here
