### ISSUE TITLE
Add flake8 to pre-commit config

### ISSUE THREAD

**Issue by jakkdl** [PyCQA/flake8-bugbear#412]
Adding flake8 to pre-commit is a small QoL that would've saved me a CI run in #405, unless there's some recursive reason why this might be problematic. Maybe if flake8-bugbear has a bug that one's PR is fixing it could be messy, but it's not terribly difficult to pass `--no-verify` or temporarily disable pre-commit locally for such cases.

**Comment by cooperlees** [comment]
We shouldn't have our own bugs ... so sure - I feel we can add away - You want to run main version and not the last released version? I'm cool either way.
