### ISSUE TITLE
Incorrect version number 24.4.6?

### ISSUE THREAD

**Issue by jenstroeger** [PyCQA/flake8-bugbear#472]
Looking at the [release history](https://github.com/PyCQA/flake8-bugbear/releases) I assume that you’re using [date-based version scheme](https://packaging.python.org/en/latest/specifications/version-specifiers/#examples-of-compliant-version-schemes) of the form `YY.mm.dd`, is that correct? If so, then I assume that Bugbear version [24.4.6](https://github.com/PyCQA/flake8-bugbear/releases/tag/24.4.26) should really be 24.4.26? The tag itself seems correct though, and so is the [declared version](https://github.com/PyCQA/flake8-bugbear/blob/d1aec4cbef7c4a49147c428b7e4a97e497b5d163/bugbear.py#L20).

So it’s just a typo in the Github release itself 🤔

**Comment by cooperlees** [comment]
Yup. But the tag itself was right, so PyPI turned out correct so I left it.
- https://pypi.org/project/flake8-bugbear/

What's this actually breaking? Is there a way to edit releases? I didn't see one, but I might be blind.

**Comment by jenstroeger** [comment]
> What's this actually breaking?

Nothing, actually. At first I thought the tag & version were also wrong and I opened this issue; while typing it up I realized that it’s all just a typo in the Release itself. So I opened the issue anyway, my OCD told me to 🤓

> Is there a way to edit releases? I didn't see one, but I might be blind.

There should be an edit icon on the far right next to the release title [here](https://github.com/PyCQA/flake8-bugbear/releases/tag/24.4.26), like in [this package](https://github.com/jenstroeger/python-package-template/releases)’s release history, no?

![gh](https://github.com/PyCQA/flake8-bugbear/assets/12053937/2cda3266-a63f-466e-a871-f88a6546d1a1)

**Comment by cooperlees** [comment]
Got it. Thanks.
