### ISSUE TITLE
Feature request: lint for dropped exception after `.add_note()`

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/flake8-bugbear#474]
```python
try:
    something()
except Exception as e:
    e.add_note("some helpful context")
```

This code is easy to write, but it has a nasty problem: you've just suppressed the exception!  I think there should be a lint warning which triggers if you `.add_note()` an exception which is not either followed by a `raise` or `raise e`, or included in a function call or rhs of an assignment expression.

**Comment by cooperlees** [comment]
Sounds sane and I welcome the PR.
