### ISSUE TITLE
Rule proposal: require explicit `strict=` argument for `itertools.batched`

### ISSUE THREAD

**Issue by tjkuson** [PyCQA/flake8-bugbear#498]
[As of Python 3.13](https://docs.python.org/3/library/itertools.html#itertools.batched), `itertools.batched` has a `strict` parameter that defaults to `False`.  By default, the batches might not be of the same size, which may cause subtle bugs. When`strict=True`, it raises `ValueError` if the final batch is not the same size as the rest.

This seems analogous to the existing rule `B905` which requires an explicit `strict=` parameter for `zip`. Hence, I think it makes sense if there is a similar rule for `itertools.batched`.

I volunteer to implement the rule, if accepted!

**Comment by JelleZijlstra** [comment]
What sort of bugs do you see this catching?

At work we have a helper function equivalent to `batched()` that's heavily used for processing large amounts of data in chunks. It's always absolutely expected that some of the batches won't be of the same size.

**Comment by tjkuson** [comment]
That's understandable! However, I don't think it is obvious to an inexperienced user or someone who hasn't read the documentation that not all batches in `itertools.batched(iterable, n)` will be of size `n`. It also isn't obvious to me what a contributor intended or expects (without `strict=`) from `itertools.batched` when reviewing code.

Off the top of my head, some examples of the uniformity of batch sizes being important include

* when the elements of a batched are unpacked, expecting `n` elements,
* when the user expects to operate on pairs,
* coordinate systems, or
* statistics.

IMO, asking users to use `strict=False` for instances where not all the batches have to be uniform is a huge problem considering it's consistent with `zip` and that `itertools.batched` hasn't been in the standard library for that long.

**Comment by tjkuson** [comment]
Sorry, didn't mean to close this! Could it be reopened (assuming you think it's worth discussing further)?

**Comment by FozzieHi** [comment]
I do see both sides of the argument, but I think on balance there's enough benefits here to create a rule. However, I think it should be opt-in like `B905` and not on by default like `B028`, then users can decide whether they think it's beneficial to their project. I think these kinds of rules do get users thinking more about how they want their implementation to work, and in this particular case would encourage them to explicitly set `strict` either to true or false depending on that use case. Obviously if it gets too noisy then they could simply not opt-in to the rule for that project.

**Comment by tjkuson** [comment]
> Is the main goal to ensure people to always set `strict=` (being more explicit)?

Yes, essentially. I had in mind `B905` except for `itertools.batched`.
