### ISSUE TITLE
Is there a way to suppress B008 for tuple subclasses

### ISSUE THREAD

**Issue by ezyang** [PyCQA/flake8-bugbear#62]
We have a class which subclasses tuple, which means that its constructor is safe to call from an argument as we will get an immutable object in return. However, B008 currently flags it. Is there a way to suppress this, without disabling the check entirely?

**Comment by joaoe** [comment]
Use
`def __init__(self, ....): # noqa: B008`

**Comment by DylanYoung** [comment]
There should be an option to specify immutable classes, much like these options in pep8-naming: https://github.com/PyCQA/pep8-naming#options

**Comment by johnthagen** [comment]
@DylanYoung 

#204 adds the `extend-immutable-calls` configuration to add additional immutable calls.

**Comment by jpy-git** [comment]
@cooperlees Think we can close this issue now given the above comment?
