### ISSUE TITLE
B950 text is misleading

### ISSUE THREAD

**Issue by jcardali** [PyCQA/flake8-bugbear#67]
B950 checks for 1.1 * `max-line-length`, but the actual error text that is returned shows just `max-line-length`

https://github.com/PyCQA/flake8-bugbear/blob/master/bugbear.py#L48

**Comment by ambv** [comment]
The point is for this to be a "highway speed limit" kind of thing. If you're overdoing it by a little, you *are* overdoing it but we are not nagging you. If you are overdoing it by a lot, we tell you the agreed max line length. If the speed limit is 65 mph, highway patrol is not going to stop you at 71 mph. But if you're going 80mph they will write a ticket for "80mph on 65mph", not "10 mph faster than reasonable".

If you want a hard limit, just use E501.
