### ISSUE TITLE
Feature Request: warning for re-raising a caught exception

### ISSUE THREAD

**Issue by firba1** [PyCQA/flake8-bugbear#72]
In python 2 if you have the following code:
```
try:
    foo()
except Exception as e:
    raise e
```
The original traceback gets swallowed. This has caused me a lot of problems and I feel like it would be useful for most developers in the ecosystem.

**Comment by joaoe** [comment]
It's January 2020 and bugbear no longer wishes to support python 2, which is also no longer supported. I agree about the problem though.

**Comment by firba1** [comment]
lol fair
