### ISSUE TITLE
This plugin cannot be used with Python 2.7 codebases

### ISSUE THREAD

**Issue by caioariede** [PyCQA/flake8-bugbear#86]
In the **README**:

> Relax, you can run flake8 with all popular plugins as a tool perfectly fine under Python 3.5+ even if you want to analyze Python 2 code. This way you'll be able to parse all of the new syntax supported on Python 3 but also effectively all the Python 2 syntax at the same time.

This is **wrong**. You cannot use flake8 installed under Python 3 with a codebase under Python 2.7, as stated in their docs:

> It is very important to install Flake8 on the correct version of Python for your needs. If you want Flake8 to properly parse new language features in Python 3.5 (for example), you need it to be installed on 3.5 for Flake8 to understand those features. In many ways, Flake8 is tied to the version of Python on which it runs.
> http://flake8.pycqa.org/en/latest/#installation

This plugin cannot be used with Python 2.7 codebases and the README should state this correctly

**Comment by cooperlees** [comment]
PR welcome. We should probably also state we'll not support Python 2 at all, come January 2020.
