### ISSUE TITLE
test_selfclean_bugbear fails with PyPI sdist

### ISSUE THREAD

**Issue by scarabeusiv** [PyCQA/flake8-bugbear#89]
When packaging the 19.8.0 release the test fails (openSUSE; python 3.7):

```
[    4s] ======================================================================
[    4s] FAIL: test_selfclean_bugbear (tests.test_bugbear.BugbearTestCase)
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/home/abuild/rpmbuild/BUILD/flake8-bugbear-19.8.0/tests/test_bugbear.py", line 200, in test_selfclean_bugbear
[    4s]     self.assertEqual(proc.returncode, 0, proc.stdout.decode("utf8"))
[    4s] AssertionError: 1 != 0 : /home/abuild/rpmbuild/BUILD/flake8-bugbear-19.8.0/bugbear.py:133:67: E203 whitespace before ':'
[    4s] 
[    4s] 
[    4s] ----------------------------------------------------------------------

```

For the complete log with the dependencies see: 
[bugbear.txt](https://github.com/PyCQA/flake8-bugbear/files/3608881/bugbear.txt)

**Comment by cooperlees** [comment]
Thanks for reporting. With this passing using Python 3.7 on CI, can you please try and ship a PR with this failing or some steps to repro please. How are you attempting to package this? Can you share those steps. Happy to potentially accept a PR that fixes this, but I feel this is most probably something in your/openSUSE environment we need to first identify.

I am unable to repro and do not have access to a openSUSE box with the information in this Issue currently.

**Comment by scarabeusiv** [comment]
We have it at https://build.opensuse.org/package/show/devel:languages:python/python-flake8-bugbear

For now I just skip the test:
https://build.opensuse.org/package/view_file/devel:languages:python/python-flake8-bugbear/python-flake8-bugbear.spec?expand=1

Looking on the list of deps:
Travis: `Successfully installed entrypoints-0.3 flake8-3.7.8 flake8-bugbear-19.8.0 mccabe-0.6.1 pycodestyle-2.5.0 pyflakes-2.1.1`
The OBS build has:
flake8 3.7.8-1.1
pycodestyle 2.5.0-1.4
entrypoints 0.3-1.3
mccabe 0.6.1-2.1

But when I chroot to the virtual machine I can trigger the problem running the flake:

```
abuild@bugaboo:~/rpmbuild/BUILD/flake8-bugbear-19.8.0> flake8 bugbear.py 
bugbear.py:133:67: E203 whitespace before ':'
```

And found the culprit in the end, the sdist archive on pypi does not contain the flake8 config: https://github.com/PyCQA/flake8-bugbear/blob/master/.flake8 so the https://github.com/PyCQA/flake8-bugbear/blob/master/MANIFEST.in should list it up.

**Comment by cooperlees** [comment]
Nice find. Will get a patch out in the next few days (or accept one) then push for you.

(I would just fix but boarding a 10 hour flight)

**Comment by scarabeusiv** [comment]
No rush; I skip the test for now (he OBS link above) as it has no big impact anyway.
