### ISSUE TITLE
Clarify why warnings "don't belong in pyflakes and pycodestyle"

### ISSUE THREAD

**Issue by l0b0** [PyCQA/flake8-bugbear#92]
Many of these seem like useful warnings, so I don't get why you say they don't belong in the main projects. Why not just make them disabled by default there?

**Comment by cooperlees** [comment]
Thanks for the question. I agree, they are useful.

The original flake8-bugbear authors (mainly @ambv) felt these lints are to opinionated and don’t have a PEP or standard behind them so a opt in plugin was decided (and I agree with that decision). Flake8 was always designed to be extended like this and allow people to add extra lints they want, so we did it this way (e.g. this were mainly done for use @ Facebook).

If you get these checks into core flake8, I’d be more than happy to pull them out here. But I expect you’d have many people disagree with you trying to add them, even disabled by default.

What’s your End goal? What do you see as the best outcome from them being added to these core tools and what do you call complete success / what does that achieve?

I don’t know how to action this issue.

**Comment by l0b0** [comment]
@cooperlees My end goal should really be world peace, but for now I'd settle for an explanation like yours in the readme :grin: Basically someone who sees this project might speculate wildly about why it's separate:

- Politics?
- Considered anti-patterns by most of the community?
- License conflict?
- Aliens/Other?

PS: The team I work on enthusiastically welcomed adding this. It was super easy and resulted in a few nice tweaks to the existing code base.
