### ISSUE TITLE
Warn on useless entries in multi-type `except` clauses

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/flake8-bugbear#98]
When using a tuple of exception types in an `except` clause, it's easy for inexperienced Pythonistas to include elements that don't have any function at all.  For example:

```python
# TypeError is a subclass of Exception, so it doesn't add anything
try: ...
except (Exception, TypeError): ...

# Duplicate exception types are useless
try: ...
except (OSError, OSError): ...

# Literal single-element tuple is pointless complexity
try: ...
except (ValueError,): ...
```

It would be nice if `flake8-bugbear` could warn about these, or at least about the first!

**Comment by cooperlees** [comment]
This sounds useful and bugbear-ish to me. Especially the first case. I’d be open to a PR for these (please remember tests).
