### ISSUE TITLE
Warn about continue/return/break in finally block

### ISSUE THREAD

**Issue by joaoe** [PyCQA/flake8-bugbear#99]
I reported this issue originally to pyflakes but they decided that is it not an error, and hence it should better be flagged as a warning by flake8-bugbear.

The issue:
```
try:
    raise ValueError(1)
finally:
  return # or break or continue
```
will silence the exception. Same with a `break` or `continue` statement in Python 3.8+, which has since been allowed in `finally` blocks. If there is a desire to silence the exception, they should explicitly be silenced in an `except` block. Putting a `if something: return` in a `finally` block is something I've done before, thinking that the exception would always be propagated, but it is actually not the case.

Another edge case
```
def a():
  try:
    return 1
  finally:
    return 2

a() = ?
```
Which value is returned ?

**References**
* original pyflakes issue about `return` in `finally` https://github.com/PyCQA/pyflakes/issues/404
* pyflakes adding support for `continue` in `finally` https://github.com/PyCQA/pyflakes/pull/476
* a PEP proposal to forbid return+continue in finally https://www.python.org/dev/peps/pep-0601/ 
* returns in finally are generally considered a bad practice. https://cwe.mitre.org/data/definitions/584.html

**Comment by cooperlees** [comment]
This seems like a good candidate for bugbear. I’d love to not have this In any of my code.

I’d merge a PR for this, but would love @ambv to agree first. Please remember tests, or it will not be merged. Thanks.

**Comment by joaoe** [comment]
I'm thinking about error code `B012`, enabled by default.
Any thoughts ?
